sign_in_success: "Login Success"
sign_in_failed: "Username or Password is incorrect"
location_success: "Location added successfully"
associate_id_issue: "Associate ID should be a number"
token_mismatch: "Access token mismatched"
date_field_empty: "Date should not be empty"


